# MCMC Parameter Configuriation File
name = 'JetSimpy'

#-------------- MODEL --------------
#---------------- E ----------------
[[model]]
name  = "Eiso"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 50.0
    upper = 56.0

#-------------- MODEL --------------
#---------------- n ----------------
[[model]]
name  = "n0"
scale = "linear"
value = 0.0

#-------------- MODEL --------------
#---------------- A ----------------
[[model]]
name  = "A"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 6.0

#-------------- MODEL --------------
#-------------- eps_e --------------
[[model]]
name  = "eps_e"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0

#-------------- MODEL --------------
#-------------- eps_b --------------
[[model]]
name  = "eps_b"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0

#-------------- MODEL --------------
#---------------- LF ---------------
[[model]]
name  = "lf"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.0

#-------------- MODEL --------------
#---------------- p ----------------
[[model]]
name  = "p"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.5
    initial_guess = 2.25
    initial_sigma = 0.25

#-------------- MODEL --------------
#------------- theta_c -------------
[[model]]
name  = "theta_c"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 0.0
    upper = 1.0

#-------------- MODEL --------------
#------------- theta_v -------------
[[model]]
name  = "theta_v"
scale = "linear"
value = 0.0

[model.prior]
    type  = "uniform"
    lower = 0.0
    upper = 1.0

#-------------- MODEL --------------
#---------------- z ----------------
[[model]]
name  = "z"
scale = "linear"
value = 0.151

#-------------- MODEL --------------
#---------------- d ----------------
[[model]]
name  = "d"
scale = "linear"
value = 742.138

#----------- EXTINCTION ------------
#---------- source_frame -----------
[[extinction]]
name  = "ebv_source_frame"
scale = "linear"

[extinction.prior]
    type  = "uniform"
    lower = 0.0
    upper = 1.0

#----------- EXTINCTION ------------
#---------- Rv Milky Way -----------
[[extinction]]
name  = "rv_milky_way"
scale = "log"

[extinction.prior]
    type  = "milkywayrv"

#----------- EXTINCTION ------------
#------------ milky_way ------------
[[extinction]]
name  = "ebv_milky_way"
scale = "linear"
value = 1.3021

#----------- CALIBRATION -----------
#------------- g1-band -------------
[[offsets]]
name  = "g1_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#------------- r1-band -------------
[[offsets]]
name  = "r1_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#------------- i1-band -------------
[[offsets]]
name  = "i1_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#------------- z1-band -------------
[[offsets]]
name  = "z1_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#------------- r2-band -------------
[[offsets]]
name  = "r2_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#------------- i2-band -------------
[[offsets]]
name  = "i2_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#------------- z2-band -------------
[[offsets]]
name  = "z2_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#----------- uvot-u-band -----------
[[offsets]]
name  = "uvot-u_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#----------- uvot-b-band -----------
[[offsets]]
name  = "uvot-b_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.02

#----------- CALIBRATION -----------
#------------ uvot-v-band ----------
[[offsets]]
name  = "uvot-v_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.02

#--------------- SLOP --------------
#--------------- slop --------------
[[slop]]
name  = "slop"
scale = "linear"

[slop.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.2
