# MCMC Parameter Configuriation File

[E]
    scale = "log"

    [E.prior]
        type  = "uniform"
        lower = -2.0
        upper = 3.0

[rho0]
    scale = "log"

    [rho0.prior]
        type  = "uniform"
        lower = -6.0
        upper = 9.0

[eps_e]
    scale = "log"

    [eps_e.prior]
        type  = "uniform"
        lower = -4.0
        upper = 0.0

[eps_b]
    scale = "log"

    [eps_b.prior]
        type  = "uniform"
        lower = -6.0
        upper = 0.0

[p]
    scale = "linear"

    [p.prior]
        type  = "uniform"
        lower = 1.5
        upper = 3.5
        initial_guess = 2.25
        initial_sigma = 0.25

[k]
    scale = "linear"

    [k.prior]
        type  = "uniform"
        lower = -1.0
        upper = 3.0

[ebv_sf]
    scale = "linear"

    [ebv_sf.prior]
        type  = "uniform"
        lower = 0.0
        upper = 1.0

[V_offset]
    scale = "linear"

    [V_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.3

[R_offset]
    scale = "linear"

    [R_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.3

[I_offset]
    scale = "linear"

    [I_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.3

[slop]
    scale = "linear"

    [slop.prior]
        type  = "uniform"
        lower = 0.0
        upper = 0.3

[X]
    scale = "linear"
    value = 0.7

[z]
    scale = "linear"
    value = 2.006

[dL]
    scale = "linear"
    value = 4.94

[ebv_mw]
    scale = "linear"
    value = 0.0647