# MCMC Parameter Configuriation File

#-------------- MODEL --------------
#---------------- E ----------------
[[model]]
name  = "E"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -2.0
    upper = 4.0
#    initial_guess = 2.13
#    initial_sigma = 0.30

#-------------- MODEL --------------
#---------------- n ----------------
[[model]]
name  = "rho0"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 6.0
#    initial_guess = -2.64
#    initial_sigma = 0.500

#-------------- MODEL --------------
#-------------- eps_e --------------
[[model]]
name  = "eps_e"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0
#    initial_guess = -0.28
#    initial_sigma = 0.28

#-------------- MODEL --------------
#-------------- eps_b --------------
[[model]]
name  = "eps_b"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0
#    initial_guess = -0.94
#    initial_sigma = 0.700

#-------------- MODEL --------------
#---------------- p ----------------
[[model]]
name  = "p"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.5
#    initial_guess = 2.01
#    initial_sigma = 0.10

#-------------- MODEL --------------
#---------------- k ----------------
[[model]]
name  = "k"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = -3.0
    upper = 3.0
#    initial_guess = 1.65
#    initial_sigma = 0.03

#-------------- MODEL --------------
#---------------- X ----------------
[[model]]
name  = "X"
scale = "linear"
value = 0.7

#-------------- MODEL --------------
#---------------- z ----------------
[[model]]
name  = "z"
scale = "linear"
value = 0.544

#-------------- MODEL --------------
#---------------- dL ---------------
[[model]]
name  = "dL"
scale = "linear"
value = 1.00

#----------- EXTINCTION ------------
#---------- source_frame -----------
[[extinction]]
name  = "ebv_source_frame"
scale = "linear"

[extinction.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.8
#    initial_guess = 0.08
#    initial_sigma = 0.01

#----------- EXTINCTION ------------
#------------ milky_way ------------
[[extinction]]
name  = "ebv_milky_way"
scale = "linear"
value = 0.022

#----------- CALIBRATION -----------
#-------------- r-band -------------
[[offsets]]
name  = "r_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- i-band -------------
[[offsets]]
name  = "i_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#------------- uvw2-band -----------
[[offsets]]
name  = "uvw2_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#------------- uvm2-band -----------
[[offsets]]
name  = "uvm2_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#------------ uvw1-band ------------
[[offsets]]
name  = "uvw1_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#----------- uvot-u-band -----------
[[offsets]]
name  = "uvot-u_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#----------- uvot-b-band -----------
[[offsets]]
name  = "uvot-b_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.02

#----------- CALIBRATION -----------
#------------ uvot-v-band ----------
[[offsets]]
name  = "uvot-v_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.02

#----------- HOST GALAXY -----------
#-------------- r-band -------------
[[host]]
name  = "r_host"
scale = "log"

[host.prior]
    type = "uniform"
    lower = -3.0
    upper = -1.0

#----------- HOST GALAXY -----------
#-------------- i-band -------------
[[host]]
name  = "i_host"
scale = "log"

[host.prior]
    type = "uniform"
    lower = -3.0
    upper = -1.0

#--------------- SLOP --------------
#--------------- slop --------------
[[slop]]
name  = "slop"
scale = "linear"
group = "uvot"

[slop.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.3

#--------------- SLOP --------------
#--------------- slop --------------
[[slop]]
name  = "slop"
scale = "linear"
group = "other"

[slop.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.15
