# MCMC Parameter Configuriation File

# -----------------------------
# ------- FREE PARAMS ---------
#------------------------------
[E]
    scale = "log"

    [E.prior]
        type  = "uniform"
        lower = -2.0
        upper = 3.0

[rho0]
    scale = "log"

    [rho0.prior]
        type  = "uniform"
        lower = -6.0
        upper = 9.0

[eps_e]
    scale = "log"

    [eps_e.prior]
        type  = "uniform"
        lower = -4.0
        upper = 0.0

[eps_b]
    scale = "log"

    [eps_b.prior]
        type  = "uniform"
        lower = -6.0
        upper = 0.0

[p]
    scale = "linear"

    [p.prior]
        type  = "uniform"
        lower = 1.5
        upper = 3.5
        initial_guess=2.5
        initial_sigma=0.5

[k]
    scale = "linear"

    [k.prior]
        type  = "uniform"
        lower = -1.0
        upper = 3.0
        initial_guess=1.0
        initial_sigma=1.0

[ebv_sf]
    scale = "linear"

    [ebv_sf.prior]
        type  = "uniform"
        lower = 0.0
        upper = 1.0

# -----------------------------
# ------- FIXED PARAMS --------
#------------------------------
[z]
    group = "observational"
    scale = "linear"
    value = 4.61

[dL]
    group = "observational"
    scale = "linear"
    value = 13.39

[X]
    group = "observational"
    scale = "linear"
    value = 0.7

[ebv_mw]
    scale = "linear"
    value = 0.05

# -----------------------------
# ---- CALIBRATION OFFSETS ----
#------------------------------
[I_offset]
    scale = "linear"

    [I_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.04

[R_offset]
    scale = "linear"

    [R_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.03

[J_offset]
    scale = "linear"

    [J_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.04

[H_offset]
    scale = "linear"

    [H_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.05

[K_offset]
    scale = "linear"

    [K_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.04

[i_offset]
    scale = "linear"

    [i_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.03

[z_offset]
    scale = "linear"

    [z_offset.prior]
        type  = "gaussian"
        mu = 0.0
        sigma = 0.04

[slop]
    scale = "linear"

    [slop.prior]
        type  = "uniform"
        lower = 0.0
        upper = 0.3

# -----------------------------
# --------- JET BREAK ---------
#------------------------------
[tj]
    scale = "log"

    [tj.prior]
        type  = "gaussian"
        mu = 4.89
        sigma = 0.064

[sj]
    scale = "linear"

    [sj.prior]
        type  = "uniform"
        lower = 0.0
        upper = 3.0
