# MCMC Parameter Configuriation File

#-------------- MODEL --------------
#---------------- E ----------------
[[model]]
name  = "E"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 0.0
    upper = 3.2
    initial_guess = 1.32
    initial_sigma = 0.40

#-------------- MODEL --------------
#----------- TRANSITION ------------
#--------------- nt ----------------
[[model]]
name  = "nt"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -4.0
    upper = 4.0
    initial_guess = 0.20
    initial_sigma = 1.00

#-------------- MODEL --------------
#----------- TRANSITION ------------
#--------------- rt ----------------
[[model]]
name  = "rt"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 16.8
    upper = 19.0
    initial_guess = 18.0
    initial_sigma = 0.4

#-------------- MODEL --------------
#-------------- eps_e --------------
[[model]]
name  = "eps_e"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -1.2
    upper = 0.0
    initial_guess = -0.38
    initial_sigma = 0.2

#-------------- MODEL --------------
#-------------- eps_b --------------
[[model]]
name  = "eps_b"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = -2.8
    initial_guess = -5.64
    initial_sigma = 1.0

#-------------- MODEL --------------
#----------------- p ----------------
[[model]]
name  = "p"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 2.4
    upper = 2.56
    initial_guess = 2.48
    initial_sigma = 0.01

#-------------- MODEL --------------
#--------------- k1i ---------------
[[model]]
name  = "k1i"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = -0.15
    upper = -0.10

#-------------- MODEL --------------
#--------------- k2 ----------------
[[model]]
name  = "k2"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = -0.8
    upper = 1.8
    initial_guess = 0.89
    initial_sigma = 0.20

#-------------- MODEL --------------
#----------- TRANSITION ------------
#--------------- sni ---------------
[[model]]
name  = "sn"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 1.0
    upper = 5.0
    initial_guess = 2.00
    initial_sigma = 0.05

#-------------- MODEL --------------
#---------------- X ----------------
[[model]]
name  = "X"
scale = "linear"
value = 0.7

#-------------- MODEL --------------
#---------------- z ----------------
[[model]]
name  = "z"
scale = "linear"
value = 0.714

#-------------- MODEL --------------
#---------------- dL ---------------
[[model]]
name  = "dL"
scale = "linear"
value = 1.386

#----------- EXTINCTION ------------
#---------- source_frame -----------
[[extinction]]
name  = "ebv_source_frame"
scale = "linear"

[extinction.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.045
    initial_guess = 0.01
    initial_sigma = 0.01

#----------- EXTINCTION ------------
#------------ milky_way ------------
[[extinction]]
name  = "ebv_milky_way"
scale = "linear"
value = 0.0279

#----------- CALIBRATION -----------
#-------------- B-band -------------
[[offsets]] # USNO B1
name  = "B_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.3

#----------- CALIBRATION -----------
#-------------- V-band -------------
[[offsets]]
name  = "V_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- R-band -------------
[[offsets]]
name  = "R_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- g-band -------------
[[offsets]]
name  = "g_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- r-band -------------
[[offsets]]
name  = "r_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- i-band -------------
[[offsets]]
name  = "i_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- z-band -------------
[[offsets]]
name  = "z_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- J-band -------------
[[offsets]]  # 2MASS
name  = "J_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- K-band -------------
[[offsets]]  # 2MASS
name  = "K_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu = 0.0
    sigma = 0.06

#--------------- SLOP --------------
#--------------- slop --------------
[[slop]]
name  = "slop"
scale = "linear"

[slop.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.1
