# MCMC Parameter Configuriation File
name = 'StratifiedFireballModel'

#-------------- MODEL --------------
#---------------- E ----------------
[[model]]
name  = "E52"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -2.0
    upper = 4.0
    initial_guess = 1.1479422928207594
    initial_sigma = 0.25

#-------------- MODEL --------------
#--------------- lfo ---------------
[[model]]
name  = "lf0"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.0

#-------------- MODEL --------------
#----------- TRANSITION ------------
#--------------- nt ----------------
[[model]]
name  = "n0t"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 6.0
    initial_guess = 0.7093638440708347
    initial_sigma = 0.25

#-------------- MODEL --------------
#----------- TRANSITION ------------
#--------------- rt ----------------
[[model]]
name  = "rt"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 15.0
    upper = 19.0
    initial_guess = 16.263273832761737
    initial_sigma = 0.25

#-------------- MODEL --------------
#-------------- eps_e --------------
[[model]]
name  = "eps_e"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0
    initial_guess = -0.3027786690747221
    initial_sigma = 0.25

#-------------- MODEL --------------
#-------------- eps_b --------------
[[model]]
name  = "eps_b"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0
    initial_guess = -1.7081007667053187
    initial_sigma = 0.25

#-------------- MODEL --------------
#----------------- p ----------------
[[model]]
name  = "p"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.0
    initial_guess = 2.0929098471237917
    initial_sigma = 0.25

#-------------- MODEL --------------
#--------------- k1 ----------------
[[model]]
name  = "k1i"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = -0.1
    upper = -1.0

#-------------- MODEL --------------
#--------------- k2 ----------------
[[model]]
name  = "k2"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 0.0
    upper = 3.0
#    initial_guess = 0.89
#    initial_sigma = 0.20

#-------------- MODEL --------------
#----------- TRANSITION ------------
#--------------- sni ---------------
[[model]]
name  = "sn"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 1.0
    upper = 5.0
#    initial_guess = 2.00
#    initial_sigma = 0.05

#-------------- MODEL --------------
#---------------- X ----------------
[[model]]
name  = "hmf"
scale = "linear"
value = 0.7

#-------------- MODEL --------------
#---------------- z ----------------
[[model]]
name  = "z"
scale = "linear"
value = 0.714

#-------------- MODEL --------------
#---------------- dL ---------------
[[model]]
name  = "dL28"
scale = "linear"
value = 1.386

#----------- EXTINCTION ------------
#---------- source_frame -----------
[[extinction]]
name  = "ebv_source_frame"
scale = "linear"

[extinction.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.2
#    initial_guess = 0.01
#    initial_sigma = 0.01

#----------- EXTINCTION ------------
#------------ milky_way ------------
[[extinction]]
name  = "ebv_milky_way"
scale = "linear"
value = 0.0279

#----------- CALIBRATION -----------
#-------------- B-band -------------
[[offsets]] # USNO B1
name  = "B_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.3

#----------- CALIBRATION -----------
#-------------- V-band -------------
[[offsets]]
name  = "V_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- R-band -------------
[[offsets]]
name  = "R_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- g-band -------------
[[offsets]]
name  = "g_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- r-band -------------
[[offsets]]
name  = "r_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- i-band -------------
[[offsets]]
name  = "i_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- z-band -------------
[[offsets]]
name  = "z_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- J-band -------------
[[offsets]]  # 2MASS
name  = "J_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- K-band -------------
[[offsets]]  # 2MASS
name  = "K_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu = 0.0
    sigma = 0.06

#--------------- SLOP --------------
#--------------- slop --------------
[[slop]]
name  = "slop"
scale = "linear"

[slop.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.2
