# MCMC Parameter Configuriation File

#-------------- MODEL --------------
#---------------- E ----------------
[[model]]
name  = "E"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 4.0

#-------------- MODEL --------------
#---------------- n ----------------
[[model]]
name  = "rho0"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -5.0
    upper = 3.0

#-------------- MODEL --------------
#-------------- eps_e --------------
[[model]]
name  = "eps_e"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -2.0
    upper = 0.0

#-------------- MODEL --------------
#-------------- eps_b --------------
[[model]]
name  = "eps_b"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = -1.5

#-------------- MODEL --------------
#---------------- p ----------------
[[model]]
name  = "p"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 2.2
    upper = 2.7
    initial_guess = 2.5
    initial_sigma = 0.03

#-------------- MODEL --------------
#---------------- k ----------------
[[model]]
name  = "k"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = -1.0
    upper = 1.6
    initial_guess = 0.6
    initial_sigma = 0.2

#-------------- MODEL --------------
#------------ tj (days) ------------
[[model]]
name  = "tj"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 0.0
    upper = 1.5

#-------------- MODEL --------------
#---------------- sj ---------------
[[model]]
name  = "sji"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 0.1
    upper = 1.0

#-------------- MODEL --------------
#---------------- X ----------------
[[model]]
name  = "X"
scale = "linear"
value = 0.7

#-------------- MODEL --------------
#---------------- z ----------------
[[model]]
name  = "z"
scale = "linear"
value = 4.61

#-------------- MODEL --------------
#---------------- dL ---------------
[[model]]
name  = "dL"
scale = "linear"
value = 13.39

#----------- EXTINCTION ------------
#---------- source_frame -----------
[[extinction]]
name  = "ebv_source_frame"
scale = "linear"

[extinction.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.2

#----------- EXTINCTION ------------
#------------ milky_way ------------
[[extinction]]
name  = "ebv_milky_way"
scale = "linear"
value = 0.05

#----------- CALIBRATION -----------
#-------------- I-band -------------
[[offsets]]
name  = "I_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- R-band -------------
[[offsets]]
name  = "R_offset"
scale = "linear"

[offsets.prior]
    type  = "uniform"
    lower = -1.0
    upper = 4.0

#----------- CALIBRATION -----------
#-------------- J-band -------------
[[offsets]]
name  = "J_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- H-band -------------
[[offsets]]
name  = "H_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.05

#----------- CALIBRATION -----------
#-------------- K-band -------------
[[offsets]]
name  = "K_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- r-band -------------
[[offsets]]
name  = "r_offset"
scale = "linear"

[offsets.prior]
    type  = "uniform"
    lower = -1.0
    upper = 3.0

#----------- CALIBRATION -----------
#-------------- i-band -------------
[[offsets]]
name  = "i_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- z-band -------------
[[offsets]]
name  = "z_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#------------- HST-band ------------
[[offsets]]
name  = "F775W_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#------------- HST-band ------------
[[offsets]]
name  = "F125W_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#--------------- SLOP --------------
#--------------- slop --------------
[[slop]]
name  = "slop"
scale = "linear"

[slop.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.1
