# Boosted Fireball Model Parameters

# ==========================
#  HYDRODYNAMIC PARAMETERS
# ==========================
[explosion_energy]
    scale = "log"
    value = 0.15869069395227384

[asymptotic_lorentz_factor]
    scale = "linear"
    value = 7.973477192135503

[boost_lorentz_factor]
    scale = "linear"
    value = 11.000923300022666

[luminosity_distance]
    scale = "linear"
    value = 0.012188

[magnetic_energy_fraction]
    scale = "log"
    value = 0.013323706571267526

[electron_energy_fraction]
    scale = "log"
    value = 0.04072783842837688

[circumburst_density]
    scale = "log"
    value = 0.0009871221028954489

[electron_energy_index]
    scale = "linear"
    value = 2.1333493591554804

[obs_angle]
    scale = "linear"
    value = 0.4769798916899842

[accelerated_electron_fraction]
    scale = "linear"

    [accelerated_electron_fraction.prior]
        type  = "uniform"
        lower = 0.99
        upper = 1.1

[redshift]
    scale = "linear"

    [redshift.prior]
        type  = "uniform"
        lower = 0.009
        upper = 0.01

[ebv_milky_way]
    scale = "linear"
    value = 0.0

[ebv_source_frame]
    scale = "linear"
    value = 0.0
