# MCMC Parameter Configuriation File
name = 'FireballModel'

#-------------- MODEL --------------
#---------------- E ----------------
[[model]]
name  = "E52"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -2.0
    upper = 4.0
#    initial_guess = 0.3554
#    initial_sigma = 0.2

#-------------- MODEL --------------
#--------------- lfo ---------------
[[model]]
name  = "lf0"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.0

#-------------- MODEL --------------
#---------------- n ----------------
[[model]]
name  = "n017"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 6.0
#    initial_guess = -0.7
#    initial_sigma = 0.5

#-------------- MODEL --------------
#-------------- eps_e --------------
[[model]]
name  = "eps_e"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0
#    initial_guess = -0.42
#    initial_sigma = 0.5

#-------------- MODEL --------------
#-------------- eps_b --------------
[[model]]
name  = "eps_b"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0
#    initial_guess = -2.0
#    initial_sigma = 0.5

#-------------- MODEL --------------
#---------------- p ----------------
[[model]]
name  = "p"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.0
#    initial_guess = 2.24
#    initial_sigma = 0.02

#-------------- MODEL --------------
#---------------- k ----------------
[[model]]
name  = "k"
scale = "linear"
[model.prior]
    type  = "uniform"
    lower = -1.0
    upper = 3.0
#    initial_guess = 1.49
#    initial_sigma = 0.07

#-------------- MODEL --------------
#------------ tj (days) ------------
[[model]]
name  = "tj"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 0.0
    upper = 1.0
#    initial_guess = 0.64
#    initial_sigma = 0.02

#-------------- MODEL --------------
#---------------- sj ---------------
[[model]]
name  = "sj"
scale = "linear"
value = 3.0

#-------------- MODEL --------------
#---------------- X ----------------
[[model]]
name  = "hmf"
scale = "linear"
value = 0.7

#-------------- MODEL --------------
#---------------- z ----------------
[[model]]
name  = "z"
scale = "linear"
value = 0.54

#-------------- MODEL --------------
#---------------- dL ---------------
[[model]]
name  = "dL28"
scale = "linear"
value = 0.9968

#----------- EXTINCTION ------------
#---------- source_frame -----------
[[extinction]]
name  = "ebv_source_frame"
scale = "linear"

[extinction.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.5

#----------- EXTINCTION ------------
#------------ milky_way ------------
[[extinction]]
name  = "ebv_milky_way"
scale = "linear"
value = 0.085

#----------- CALIBRATION -----------
#-------------- B-band -------------
[[offsets]]
name  = "B_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- V-band -------------
[[offsets]]
name  = "V_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- R-band -------------
[[offsets]]
name  = "R_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- i-band -------------
[[offsets]]
name  = "i_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#--------------- SLOP --------------
#--------------- slop --------------
[[slop]]
name  = "slop"
scale = "linear"

[slop.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.1
#    initial_guess = 0.02
#    initial_sigma = 0.001