# MCMC Parameter Configuriation File
name = 'FireballModel'

#-------------- MODEL --------------
#---------------- E ----------------
[[model]]
name  = "E52"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -2.0
    upper = 4.0
    initial_guess = 1.46845276
    initial_sigma = 0.25

#-------------- MODEL --------------
#--------------- lfo ---------------
[[model]]
name  = "lf0"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.0

#-------------- MODEL --------------
#---------------- n ----------------
[[model]]
name  = "n017"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 6.0
    initial_guess = 0.16156396
    initial_sigma = 0.25

#-------------- MODEL --------------
#-------------- eps_e --------------
[[model]]
name  = "eps_e"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0
    initial_guess = -0.77176278
    initial_sigma = 0.25

#-------------- MODEL --------------
#-------------- eps_b --------------
[[model]]
name  = "eps_b"
scale = "log"

[model.prior]
    type  = "uniform"
    lower = -6.0
    upper = 0.0
    initial_guess = -1.94798736
    initial_sigma = 0.25

#-------------- MODEL --------------
#---------------- p ----------------
[[model]]
name  = "p"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = 2.0
    upper = 3.0
    initial_guess = 2.0372483307341684
    initial_sigma = 0.25

#-------------- MODEL --------------
#---------------- k ----------------
[[model]]
name  = "k"
scale = "linear"

[model.prior]
    type  = "uniform"
    lower = -1.0
    upper = 3.0
    initial_guess = 1.8475128681551616
    initial_sigma = 0.25

#-------------- MODEL --------------
#---------------- X ----------------
[[model]]
name  = "hmf"
scale = "linear"
value = 0.7

#-------------- MODEL --------------
#---------------- z ----------------
[[model]]
name  = "z"
scale = "linear"
value = 1.293

#-------------- MODEL --------------
#---------------- dL ---------------
[[model]]
name  = "dL28"
scale = "linear"
value = 2.88

#----------- EXTINCTION ------------
#---------- source_frame -----------
[[extinction]]
name  = "ebv_source_frame"
scale = "linear"

[extinction.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.5
#    initial_guess = 0.00465
#    initial_sigma = 0.004

#----------- EXTINCTION ------------
#------------ milky_way ------------
[[extinction]]
name  = "ebv_milky_way"
scale = "linear"
value = 0.0493

#----------- CALIBRATION -----------
#-------------- R-band -------------
[[offsets]]
name  = "R_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.3

#----------- CALIBRATION -----------
#-------------- J-band -------------
[[offsets]]
name  = "J_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- H-band -------------
[[offsets]]
name  = "H_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.05

#----------- CALIBRATION -----------
#-------------- B-band -------------
[[offsets]]
name  = "B_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#----------- CALIBRATION -----------
#-------------- r-band -------------
[[offsets]]
name  = "r_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- i-band -------------
[[offsets]]
name  = "i_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.03

#----------- CALIBRATION -----------
#-------------- z-band -------------
[[offsets]]
name  = "z_offset"
scale = "linear"

[offsets.prior]
    type  = "gaussian"
    mu    = 0.0
    sigma = 0.04

#--------------- SLOP --------------
#--------------- slop --------------
[[slop]]
name  = "slop"
scale = "linear"

[slop.prior]
    type  = "uniform"
    lower = 0.0
    upper = 0.2
#    initial_guess = 0.044
#    initial_sigma = 0.02
